[package]
name = "waffle-extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
logos = "0.13.0"
rustyline = "11.0.0"
wabt = "0.10.0"
waffle = "0.0.22"
wasmer = "3.3.0"
